# Generated by Django 2.0.2 on 2018-02-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='systems',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='time',
            name='description',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='fio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='users',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
