# Generated by Django 2.0.2 on 2018-02-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FullTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_id', models.IntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.IntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_id', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('fio', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('position', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='fulltable',
            name='priotiry',
            field=models.ManyToManyField(to='logic.Priority'),
        ),
        migrations.AddField(
            model_name='fulltable',
            name='system',
            field=models.ManyToManyField(to='logic.Systems'),
        ),
        migrations.AddField(
            model_name='fulltable',
            name='time',
            field=models.ManyToManyField(to='logic.Time'),
        ),
        migrations.AddField(
            model_name='fulltable',
            name='user',
            field=models.ManyToManyField(to='logic.Users'),
        ),
    ]
